/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004f54",
        "on-tertiary": "#3c0090",
        "on-surface-variant": "#b9cacb",
        "surface-dim": "#0d1419",
        "surface-variant": "#2f363b",
        "error": "#ffb4ab",
        "secondary-container": "#32495f",
        "on-error": "#690005",
        "surface": "#0d1419",
        "primary-fixed": "#74f5ff",
        "on-secondary-fixed-variant": "#32495f",
        "inverse-surface": "#dde3eb",
        "tertiary-fixed-dim": "#d1bcff",
        "surface-container": "#1a2026",
        "on-surface": "#dde3eb",
        "outline": "#849495",
        "tertiary": "#fcf5ff",
        "on-primary-container": "#006a71",
        "surface-container-highest": "#2f363b",
        "surface-container-high": "#242b30",
        "on-background": "#dde3eb",
        "surface-container-low": "#161c22",
        "secondary-fixed": "#cee5ff",
        "on-secondary-fixed": "#031d31",
        "on-secondary-container": "#a0b7d2",
        "on-tertiary-fixed": "#23005b",
        "on-primary-fixed": "#002022",
        "inverse-primary": "#00696f",
        "surface-tint": "#00dbe7",
        "surface-bright": "#333a40",
        "error-container": "#93000a",
        "tertiary-container": "#e3d4ff",
        "on-tertiary-fixed-variant": "#5700c9",
        "on-error-container": "#ffdad6",
        "on-secondary": "#1b3247",
        "secondary": "#b1c9e3",
        "on-tertiary-container": "#7318ff",
        "background": "#050B10",
        "primary-container": "#00f2ff",
        "surface-container-lowest": "#080f14",
        "primary": "#e1fdff",
        "primary-fixed-dim": "#00dbe7",
        "outline-variant": "#3a494b",
        "on-primary": "#00363a",
        "tertiary-fixed": "#e9ddff",
        "inverse-on-surface": "#2a3137",
        "secondary-fixed-dim": "#b1c9e3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
        unit: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
